CREATE TABLE "squad" (
                          "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "name" varchar UNIQUE,
                          "maxSize" int DEFAULT 5,
                          "cause" varchar,
                          "deleted" boolean DEFAULT false
);

CREATE TABLE "hero" (
                          "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "name" varchar UNIQUE,
                          "age" int,
                          "squadId" int,
                          "strengthId" int,
                          "weaknessId" int,
                          "deleted" boolean DEFAULT false
);


CREATE TABLE "strength" (
                             "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             "name" varchar UNIQUE,
                             "score" DOUBLE PRECISION,
                             "deleted" boolean DEFAULT false
);

CREATE TABLE "weakness" (
                            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "name" varchar UNIQUE,
                            "score" DOUBLE PRECISION,
                            "deleted" boolean DEFAULT false
);


ALTER TABLE "hero" ADD FOREIGN KEY ("squadId") references "squad" ("id");
ALTER TABLE "hero" ADD FOREIGN KEY ("strengthId") references "strength" ("id");
ALTER TABLE "hero" ADD FOREIGN KEY ("weaknessId") references "weakness" ("id");


-- Sample Strengths
INSERT INTO strength (name, score) VALUES ('FEARLESS', 10);
INSERT INTO strength (name, score) VALUES ('RUNNING', 10);
INSERT INTO strength (name, score) VALUES ('WEAPONS', 20);
INSERT INTO strength (name, score) VALUES ('KARATE', 5);

--Sample Weakness

INSERT INTO weakness (name, score) VALUES ('FEAR', -20);
INSERT INTO weakness (name, score) VALUES ('VENOM', -10);
INSERT INTO weakness (name, score) VALUES ('HEIGHTS', -20);
INSERT INTO weakness (name, score) VALUES ('SUN', 5);

-- Sample Squads

INSERT INTO squad (name, maxSize, cause) VALUES ('avengers', 7, 'saving the world');
INSERT INTO squad (name, maxSize, cause) VALUES ('ninja turtles', 4, 'fights');

-- Sample Heroes

INSERT INTO hero (name, age) VALUES ('Ironman', 45);
INSERT INTO hero (name, age) VALUES ('Thor', 40);
INSERT INTO hero (name, age) VALUES ('Captain America', 35);
INSERT INTO hero (name, age) VALUES ('Wonder Woman', 30);
INSERT INTO hero (name, age) VALUES ('Thanos', 50);